apiVersion: skaffold/v2alpha3
kind: Config
deploy: 
  kubectl: 
    manifests: 
      - ./infra/k8s/*
build:
  local: 
    push: false 
  artifacts: 
    - image: eugenedocker325/client
      context: client 
      docker: 
        dockerfile: Dockerfile
      sync:
        manual: 
          - src: 'src/**/*.js'
            dest: .
    - image: eugenedocker325/comments
      context: comments 
      docker: 
        dockerfile: Dockerfile
      sync:
        manual: 
          - src: '*.js'
            dest: .
    - image: eugenedocker325/event-bus
      context: event-bus 
      docker: 
        dockerfile: Dockerfile
      sync:
        manual: 
          - src: '*.js'
            dest: .
    - image: eugenedocker325/moderate
      context: moderate
      docker: 
        dockerfile: Dockerfile
      sync:
        manual: 
          - src: '*.js'
            dest: .
    - image: eugenedocker325/posts
      context: posts
      docker: 
        dockerfile: Dockerfile
      sync:
        manual: 
          - src: '*.js'
            dest: .
    - image: eugenedocker325/query
      context: query
      docker: 
        dockerfile: Dockerfile
      sync:
        manual: 
          - src: '*.js'
            dest: .